insert into INTERNSHIP_202211.T_USER(ID,FULLNAME,ICON,MIMETYPE,ADMINFLG,ADDRESS,KENGENCODE,PAYMENTID,MAILADDRESS) values ('0','Tanaka Tarou',null,null,'1','Ibaraki','1','2','a@gmail.com');
insert into INTERNSHIP_202211.T_USER(ID,FULLNAME,ICON,MIMETYPE,ADMINFLG,ADDRESS,KENGENCODE,PAYMENTID,MAILADDRESS) values ('1','Satoh Jiroh',null,null,'0','U.S.','0','1','b@gmail.com');
insert into INTERNSHIP_202211.T_USER(ID,FULLNAME,ICON,MIMETYPE,ADMINFLG,ADDRESS,KENGENCODE,PAYMENTID,MAILADDRESS) values ('2','Kajiwara Hiroshi',null,null,'0','Tochigi','0','1','a@yahoo.co.jp');
insert into INTERNSHIP_202211.T_USER(ID,FULLNAME,ICON,MIMETYPE,ADMINFLG,ADDRESS,KENGENCODE,PAYMENTID,MAILADDRESS) values ('3','佐藤　花子',null,null,'0','Texas','0','1',null);
insert into INTERNSHIP_202211.T_USER(ID,FULLNAME,ICON,MIMETYPE,ADMINFLG,ADDRESS,KENGENCODE,PAYMENTID,MAILADDRESS) values ('4','加藤　一子',null,null,'0','Hitachi','0','0','c@gmai.com');
insert into INTERNSHIP_202211.T_USER(ID,FULLNAME,ICON,MIMETYPE,ADMINFLG,ADDRESS,KENGENCODE,PAYMENTID,MAILADDRESS) values ('5','加藤　一子',null,null,'0','Hitachi','0','0','c@gmai.com');
insert into INTERNSHIP_202211.T_USER(ID,FULLNAME,ICON,MIMETYPE,ADMINFLG,ADDRESS,KENGENCODE,PAYMENTID,MAILADDRESS) values ('6','Nemoto Saburoh',null,null,'1',null,null,null,null);
insert into INTERNSHIP_202211.T_USER(ID,FULLNAME,ICON,MIMETYPE,ADMINFLG,ADDRESS,KENGENCODE,PAYMENTID,MAILADDRESS) values ('7','田中太郎',null,null,'1','Ibaraki, Japan','0','1','d@gmail.com');
insert into INTERNSHIP_202211.T_USER(ID,FULLNAME,ICON,MIMETYPE,ADMINFLG,ADDRESS,KENGENCODE,PAYMENTID,MAILADDRESS) values ('8','ティ・エス・太郎',null,null,'0',null,'1','2','c@yahoo.co.jp');
