CREATE TABLE "T_USER" 
(
	"ID" VARCHAR2(10) NOT NULL ENABLE, 
	"FULLNAME" VARCHAR2(50), 
	"ICON" BLOB, 
	"MIMETYPE" VARCHAR2(100), 
	"ADMINFLG" VARCHAR2(1) NOT NULL ENABLE, 
	"ADDRESS" VARCHAR2(100), 
	"KENGENCODE" VARCHAR2(5), 
	"PAYMENTID" VARCHAR2(5), 
	"MAILADDRESS" VARCHAR2(100), 
	 PRIMARY KEY ("ID")
);

CREATE TABLE "T_LOGIN" 
(	
	"ID" VARCHAR2(10) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(20) NOT NULL ENABLE, 
	 PRIMARY KEY ("ID")
);

CREATE TABLE "T_KENGEN" 
(	
	"CODE" VARCHAR2(2) NOT NULL ENABLE, 
	"NAME" VARCHAR2(10)
);

CREATE TABLE "T_TIMETABLE" 
(	
	"ID" VARCHAR2(5) NOT NULL ENABLE, 
	"DIRECTION" VARCHAR2(10), 
	"HITACHI_TIME" VARCHAR2(10), 
	"HITACHITAGA_TIME" VARCHAR2(10), 
	"TOKYO_TIME" VARCHAR2(10), 
	"UENO_TIME" VARCHAR2(10), 
	 PRIMARY KEY ("ID")
);

CREATE TABLE "T_RESERVE" 
(	
	"ID" VARCHAR2(5) NOT NULL ENABLE, 
	"DATEANDTIMEID" VARCHAR2(5), 
	"STARTPOINTID" VARCHAR2(5), 
	"ENDPOINTID" VARCHAR2(5), 
	"SEAT" VARCHAR2(10), 
	"PRICE" NUMBER, 
	"USERID" VARCHAR2(5), 
	"ISCANCEL" VARCHAR2(1), 
	 PRIMARY KEY ("ID")
);

CREATE TABLE "T_POINT" 
(
	"ID" VARCHAR2(5) NOT NULL ENABLE, 
	"NAME" VARCHAR2(50), 
	 PRIMARY KEY ("ID")
);

CREATE TABLE "T_PAYMENT" 
(	
	"ID" VARCHAR2(5) NOT NULL ENABLE, 
	"NAME" VARCHAR2(50), 
	 PRIMARY KEY ("ID")
);

CREATE TABLE "T_DATEANDTIME" 
(	
	"ID" VARCHAR2(5) NOT NULL ENABLE, 
	"TIMETABLEID" VARCHAR2(5) NOT NULL ENABLE, 
	"YMD" DATE, 
	 PRIMARY KEY ("ID")
);