//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Internship_Template.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Internship_202211 : DbContext
    {
        public Internship_202211()
            : base("name=Internship_202211")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_DATEANDTIME> T_DATEANDTIME { get; set; }
        public virtual DbSet<T_KENGEN> T_KENGEN { get; set; }
        public virtual DbSet<T_LOGIN> T_LOGIN { get; set; }
        public virtual DbSet<T_PAYMENT> T_PAYMENT { get; set; }
        public virtual DbSet<T_POINT> T_POINT { get; set; }
        public virtual DbSet<T_RESERVE> T_RESERVE { get; set; }
        public virtual DbSet<T_TIMETABLE> T_TIMETABLE { get; set; }
        public virtual DbSet<T_USER> T_USER { get; set; }
    }
}
