//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Internship_Template.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class T_RESERVE
    {
        public string ID { get; set; }
        public string DATEANDTIMEID { get; set; }
        public string STARTPOINTID { get; set; }
        public string ENDPOINTID { get; set; }
        public string SEAT { get; set; }

        [DisplayFormat(DataFormatString = "{0:0}", ApplyFormatInEditMode = true)]

        public Nullable<decimal> PRICE { get; set; }
        public string USERID { get; set; }
        public string ISCANCEL { get; set; }
    
        public virtual T_USER T_USER { get; set; }
        public virtual T_POINT T_POINT { get; set; }
        public virtual T_POINT T_POINTEND { get; set; }
        public virtual T_DATEANDTIME T_DATEANDTIME { get; set; }
    }
}
