//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Internship_Template.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TEST
    {
        public decimal ID { get; set; }
        public Nullable<decimal> SCORE { get; set; }
        public string GRADE { get; set; }
        public string TANABE { get; set; }
    }
}
