//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Internship_Template.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_USER()
        {
            this.T_RESERVE = new HashSet<T_RESERVE>();
        }
    
        public string ID { get; set; }
        public string FULLNAME { get; set; }
        public byte[] ICON { get; set; }
        public string MIMETYPE { get; set; }
        public string ADMINFLG { get; set; }
        public string ADDRESS { get; set; }
        public string KENGENCODE { get; set; }
        public string PAYMENTID { get; set; }
        public string MAILADDRESS { get; set; }
    
        public virtual T_LOGIN T_LOGIN { get; set; }
        public virtual T_KENGEN T_KENGEN { get; set; }
        public virtual T_PAYMENT T_PAYMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_RESERVE> T_RESERVE { get; set; }
    }
}
